services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - internal
  php:
    image: php:8.3.9-fpm-alpine
    volumes:
      - ./src:/var/www/html
    networks:
      - internal
networks:
  internal:
    driver: bridge
