services:
  your-service-name-here:
    volumes:
      - .:/workspace:cached

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    command: /bin/sh -c "while sleep 1000; do :; done"